config/routes.rb
Rails.application.routes.draw do
  get 'purchase/index'
  get 'purchase/done'
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'items#index'

  resources :signup do
    collection do
      get 'signup'
      get 'signup2'
      get 'signup3'
      get 'signup4'
      get 'signup5'
      get 'signup6'
      get 'signup7'
    end
  end


  resources :items do

    collection do
      get 'search'
      post 'search'
    end
    member do
      get 'purchase'
    end
  end





  resources :users, only: [:show, :identification, :index, :new]

  resources :profiles, only: [:show]

  resources :identifications, only: [:show]

  resources :creditcards, only: [:new, :show] do
    collection do
      post 'show', to: 'creditcards#show'
      post 'pay', to: 'creditcards#pay'
      post 'delete', to: 'creditcards#delete'
    end
    member do
      post 'buy'
    end
  end

  
  
  get 'mypage',to:'mypage#index' 
  namespace :mypage do
    get 'profile'
    put 'profile_update'
    get 'card'
    get 'identification'
    get 'logout'
  end
  
end

app/controllers/signup_controller.rb
class SignupController < ApplicationController

  def signup2
    @user = User.new
  end

  def signup3
    session[:nickname] = user_params[:nickname]
    session[:email] = user_params[:email]
    session[:password] = user_params[:password]
    session[:password_confirmation] = user_params[:password_confirmation]
    session[:firstname] = user_params[:firstname]
    session[:lastname] = user_params[:lastname]
    session[:firstname_kana] = user_params[:firstname_kana]
    session[:lastname_kana] = user_params[:lastname_kana]
    session[:birthday] = user_params["birthday(1i)"]+"/"+user_params["birthday(2i)"]+"/"+user_params["birthday(3i)"]
    @user = User.new
  end

  def signup4
    session[:phone_number] = user_params[:phone_number]
    @user = User.new
  end


  def signup5
    @user = User.new
    @address = CustAddresss.new
    
  end

  def signup6
    session[:cfirstname] = address_params[:firstname]
    session[:clastname] = address_params[:lastname]
    session[:cfirstname_kana] = address_params[:firstname_kana]
    session[:clastname_kana] = address_params[:lastname_kana]
    session[:cpostal_code] = address_params[:postal_code]
    session[:cprefecture] = address_params[:prefecture]
    session[:cmunicipality] = address_params[:municipality]
    session[:chouse_number] = address_params[:house_number]
    session[:cbuilding_name] = address_params[:building_name]
    session[:cphone_number] = address_params[:phone_number]
    @user = User.new
    @address = CustAddresss.new
  end

  def signup7
    @user = User.new
    @address = CustAddresss.new
  end

  def create
    @user = User.new(
      nickname: session[:nickname],
      email:    session[:email],
      password: session[:password],
      password_confirmation: session[:password_confirmation],
      firstname:session[:firstname],
      lastname: session[:lastname],
      firstname_kana: session[:firstname_kana],
      lastname_kana: session[:lastname_kana],
      birthday: session[:birthday],
      phone_number: session[:phone_number]
    )
    @address = CustAddresss.new(
      firstname:session[:cfirstname],
      lastname:session[:clastname],
      firstname_kana:session[:cfirstname_kana],
      lastname_kana:session[:clastname_kana],
      postal_code:session[:cpostal_code],
      prefecture:session[:cprefecture],
      municipality:session[:cmunicipality],
      house_number:session[:chouse_number],
      building_name:session[:cbuilding_name],
      phone_number:session[:cphone_number]
    )
    if @user.save
      @address.save
      sign_in @user
      redirect_to signup7_signup_index_path
    else
      redirect_to signup2_signup_index_path
    end
  end

  private
  def user_params
    params.require(:user).permit(
      :nickname,
      :email,
      :password,
      :password_confirmation,
      :firstname,
      :lastname,
      :firstname_kana,
      :lastname_kana,
      "birthday(1i)",
      "birthday(2i)",
      "birthday(3i)",
      :phone_number
    )
  end

  def address_params
    params.require(:cust_addresss).permit(
      :firstname,
      :lastname,
      :firstname_kana,
      :lastname_kana,
      :postal_code,
      :prefecture,
      :municipality,
      :house_number,
      :building_name,
      :phone_number
    )
  end
end

app/views/signup/signup.html.haml
.header-first
  .header-first__logo
    = link_to "#" do
      = image_tag "//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?891577966", class: 'header-first__logo__icon'

.main-first
  .main-first__block
    %h2.main-first__block__message
      新規会員登録
    .main-first__block__contents
      %ul.main-first__block__contents__list
        %li.main-first__block__contents__list__signup-btn--mail
          = link_to signup2_signup_index_path do
            %i.icon.fa.fa-envelope 
            メールアドレスで登録する
        %li.main-first__block__contents__list__signup-btn--facebook
          = link_to user_facebook_omniauth_authorize_path, method: :post do
            %i.fa.fa-facebook
            Facebookで登録する
        %li.main-first__block__contents__list__signup-btn--google
          = link_to user_google_oauth2_omniauth_authorize_path, method: :post do
            Googleで登録する

.footer-first
  %ul.footer-first__sections
    %li.footer-first__sections__list
      = link_to "プライバシーポリシー" ,"#"
    %li.footer-first__sections__list
      = link_to "メルカリ利用規約" ,"#"
    %li.footer-first__sections__list
      = link_to "特定商取引に関する表記" ,"#"
  .footer-first__logo
    = link_to "#" do
      = image_tag '//www-mercari-jp.akamaized.net/assets/img/common/common/logo-gray.svg?891577966', class: 'footer__logo__icon'
  %P.footer-first__data
    © 2019 Mercari

app/views/signup/signup2.html.haml
.header-secound
  .header-secound__logo
    = link_to "#" do
      = image_tag "//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?891577966", class: 'header-secound__logo__icon'
  .header-secound__signup-bar
    %ol.header-secound__signup-bar__stepber
      %li.header-secound__signup-bar__stepber--first.red-color-text
        会員情報
        .bubble.red-color
          %span
      %li.header-secound__signup-bar__stepber--secound
        電話番号認証
        .bubble
          %span
      %li.header-secound__signup-bar__stepber--third
        お届け先住所入力
        .bubble
          %span
      %li.header-secound__signup-bar__stepber--forth
        支払い方法
        .bubble
          %span
      %li.header-secound__signup-bar__stepber--fifth
        完了
        .bubble
.main-secound
  .main-secound__block
    %h2.main-secound__block__title
      会員情報入力
  .main-secound__contents
    .main-secound__contents__container
      = form_for @user, url: signup3_signup_index_path, method: :get do |f|
        .main-secound__contents__container__block
          %p.main-secound__contents__container__block__text
            ニックネーム
          %p.main-secound__contents__container__block__require
            必須
          .main-secound__contents__container__block__form
            = f.text_field :nickname ,placeholder:"例) メルカリ嵩将" , class:'input-place'
        .main-secound__contents__container__block
          %p.main-secound__contents__container__block__text
            メールアドレス
          %p.main-secound__contents__container__block__require
            必須
          .main-secound__contents__container__block__form
            = f.email_field :email ,placeholder:"PC・携帯どちらでも可", class:'input-place'
        .main-secound__contents__container__block
          %p.main-secound__contents__container__block__text
            パスワード
          %p.main-secound__contents__container__block__require
            必須
          .main-secound__contents__container__block__form
            = f.password_field :password ,placeholder:"6文字以上",class:'input-place'
        .main-secound__contents__container__block
          %p.main-secound__contents__container__block__text
            パスワード(確認)
          %p.main-secound__contents__container__block__require
            必須
          .main-secound__contents__container__block__form
            = f.password_field :password_confirmation ,placeholder:"6文字以上",class:'input-place'
        .main-secound__contents__container__block
          %h3.main-secound__contents__container__block__title
            本人確認
          %p.main-secound__contents__container__block__description
            安心・安全にご利用いただくために、お客さまの本人情報の登録にご協力ください。他のお客さまに公開されることはありません。
        .main-secound__contents__container__block
          %p.main-secound__contents__container__block__text
            お名前（全角）
          %p.main-secound__contents__container__block__require
            必須
          .main-secound__contents__container__block__form-half
            = f.text_field :firstname ,placeholder:"例）徳川" ,class:'input-place'
            = f.text_field :lastname ,placeholder:"例）家康" ,class:'input-place'
        .main-secound__contents__container__block
          %p.main-secound__contents__container__block__text
            お名前カナ（全角）
          %p.main-secound__contents__container__block__require
            必須
          .main-secound__contents__container__block__form-half
            = f.text_field :firstname_kana ,placeholder:"例）トクガワ" ,class:'input-place'
            = f.text_field :lastname_kana ,placeholder:"例）イエヤス" ,class:'input-place'
        .main-secound__contents__container__block
          %p.main-secound__contents__container__block__text
            生年月日
          %p.main-secound__contents__container__block__require
            必須
        .main-secound__contents__container__block__form
          %label.arrow1{for: 'user_birthday_1i'} 
            %i.fa.fa-chevron-down
          %label.arrow2{for: 'user_birthday_2i'} 
            %i.fa.fa-chevron-down
          %label.arrow3{for: 'user_birthday_3i'} 
            %i.fa.fa-chevron-down
          .main-secound__contents__container__block__form--select-boxs
            -# = raw sprintf(f.date_select(:birthday, start_year: 1920, end_year: Time.now.year, :use_month_numbers => true, :date_separator => '%s'),'年','月')
            = raw sprintf(f.date_select(:birthday,with_css_classes:'birthday',use_month_numbers: true,start_year: 1920,end_year: Time.now.year,prompt:"--" ,date_separator: '%s'),'年 ', '月 ') + '日'
            -#   %select.year-js
            -#     %option{value: ""} --
            -#     - number = 2019
            -#     - while number >= 1900 do
            -#       %option{value: "#{number}"} 
            -#         = number
            -#       - number -= 1
            -#   %span.word
            -#     年
            -# .main-secound__contents__container__block__form--select-box
            -#   %select.month-js
            -#     %option{value: ""} --
            -#     - number = 1
            -#     - while number <= 12 do
            -#       %option{value: "#{number}"} 
            -#         = number
            -#       - number += 1
            -#   %span.word
            -#     月
            -# .main-secound__contents__container__block__form--select-box
            -#   %select.day-js
            -#     %option{value: ""} --
            -#     - number = 1
            -#     - while number <= 31 do
            -#       %option{value: "#{number}"} 
            -#         = number
            -#       - number += 1
            -#   %span.word
            -#     日
        .main-secound__contents__container__block
          %p.main-secound__contents__container__block__info
            ※ 本人情報は正しく入力してください。会員登録後、修正するにはお時間を頂く場合があります。
        .main-secound__contents__container__block
          .main-secound__contents__container__block__authentication
            .main-secound__contents__container__block__authentication__white-box
            %p.main-secound__contents__container__block__authentication__text
              私はロボットではありません。
            .main-secound__contents__container__block__authentication__icon
              .main-secound__contents__container__block__authentication__icon__image
              %p.main-secound__contents__container__block__authentication__icon__name
                reCAPTCHA
            .main-secound__contents__container__block__authentication__link-block
              = link_to "プライバシー", "https://www.google.com/intl/ja/policies/privacy/" ,class:'link-gray'
              %span.link-gray
                -
              = link_to "利用規約","https://www.google.com/intl/ja/policies/terms/" ,class:'link-gray'
        .main-secound__contents__container__block
          %p.main-secound__contents__container__block__text-message
            「次へ進む」のボタンを押すことにより、
            = link_to "利用規約", "https://www.mercari.com/jp/tos_list/" ,class: 'link-blue'
            同意したものとします
        .main-secound__contents__container__block
          .main-secound__contents__container__block__btn-next
            = f.submit "次へ進む" ,class:'link-white'
        .main-secound__contents__container__block.text-right
          .main-secound__contents__container__block--information
            = link_to "#" ,class:'link-blue' do
              本人情報の登録について
              %i.fa.fa-chevron-right
.footer-first
  %ul.footer-first__sections
    %li.footer-first__sections__list
      = link_to "プライバシーポリシー" ,"#"
    %li.footer-first__sections__list
      = link_to "メルカリ利用規約" ,"#"
    %li.footer-first__sections__list
      = link_to "特定商取引に関する表記" ,"#"
  .footer-first__logo
    = link_to "#" do
      = image_tag '//www-mercari-jp.akamaized.net/assets/img/common/common/logo-gray.svg?891577966', class: 'footer__logo__icon'
  %P.footer-first__data
    © 2019 Mercari

app/views/signup/signup3.html.haml
.header-secound
  .header-secound__logo
    = link_to "#" do
      = image_tag "//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?891577966", class: 'header-secound__logo__icon'
  .header-secound__signup-bar
    %ol.header-secound__signup-bar__stepber
      %li.header-secound__signup-bar__stepber--first
        会員情報
        .bubble.red-color
          %span.red-color
      %li.header-secound__signup-bar__stepber--secound.red-color-text
        電話番号認証
        .bubble.red-color
          %span
      %li.header-secound__signup-bar__stepber--third
        お届け先住所入力
        .bubble
          %span
      %li.header-secound__signup-bar__stepber--forth
        支払い方法
        .bubble
          %span
      %li.header-secound__signup-bar__stepber--fifth
        完了
        .bubble
.main-secound
  .main-secound__block
    %h2.main-secound__block__title
      電話番号の確認
  .main-secound__contents
    .main-secound__contents__container
      = form_for @user, url: signup4_signup_index_path, method: :get do |f|
        .main-secound__contents__container__block
          %p.main-secound__contents__container__block__text
            携帯電話の番号
          %p.main-secound__contents__container__block__require
            必須
          .main-secound__contents__container__block__form
            = f.text_field :phone_number ,placeholder:"携帯電話の番号を入力", class:"input-place"
          %p.main-secound__contents__container__block__description
            本人確認のため、携帯電話のSMS(ショートメッセージサービス)を利用して認証を行います。
        .main-secound__contents__container__block
          .main-secound__contents__container__block__btn-next
            = f.submit "SMSを送信する" ,class:'link-white'
          %p.main-secound__contents__container__block__description
            ※電話番号は本人確認や不正利用防止のために利用します。他のユーザーに公開されることはありません。
        .main-secound__contents__container__block.text-right
          .main-secound__contents__container__block--information
            = link_to "#" ,class:'link-blue' do
              電話番号の確認が必要な理由
              %i.fa.fa-chevron-right

.footer-first
  %ul.footer-first__sections
    %li.footer-first__sections__list
      = link_to "プライバシーポリシー" ,"#"
    %li.footer-first__sections__list
      = link_to "メルカリ利用規約" ,"#"
    %li.footer-first__sections__list
      = link_to "特定商取引に関する表記" ,"#"
  .footer-first__logo
    = link_to "#" do
      = image_tag '//www-mercari-jp.akamaized.net/assets/img/common/common/logo-gray.svg?891577966', class: 'footer__logo__icon'
  %P.footer-first__data
    © 2019 Mercari

app/views/signup/signup4.html.haml
.header-secound
  .header-secound__logo
    = link_to "#" do
      = image_tag "//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?891577966", class: 'header-secound__logo__icon'
  .header-secound__signup-bar
    %ol.header-secound__signup-bar__stepber
      %li.header-secound__signup-bar__stepber--first
        会員情報
        .bubble.red-color
          %span.red-color
      %li.header-secound__signup-bar__stepber--secound.red-color-text
        電話番号認証
        .bubble.red-color
          %span
      %li.header-secound__signup-bar__stepber--third
        お届け先住所入力
        .bubble
          %span
      %li.header-secound__signup-bar__stepber--forth
        支払い方法
        .bubble
          %span
      %li.header-secound__signup-bar__stepber--fifth
        完了
        .bubble
.main-secound
  .main-secound__block
    %h2.main-secound__block__title
      電話番号認証
  .main-secound__contents.bottom-space
    .main-secound__contents__container
      = form_for @user, url: signup5_signup_index_path, method: :get do |f|
        .main-secound__contents__container__block
          %p.main-secound__contents__container__block__text
            認証番号
          .main-secound__contents__container__block__form
            %input.input-place{placeholder:"認証番号番を入力", type:"text"}
          %p.main-secound__contents__container__block__description
            SMSで届いた認証番号を入力してください
        .main-secound__contents__container__block
          .main-secound__contents__container__block__btn-next
            = f.submit "認証して完了" ,class:'link-white'
    .main-secound__contents.bottom-space
      .main-secound__contents__container
        .main-secound__contents__container__block
          %p.main-secound__contents__container__block__text
            30秒たっても認証番号が届かない方へ
          %p.main-secound__contents__container__block__description
            電話で認証番号を聞くこともできます。
        .main-secound__contents__container__block  
          .main-secound__contents__container__block__btn-next
            = link_to "電話で認証番号を聞く（通話無料）" ,"signup4" ,class:'link-white'
    .main-secound__contents.bottom-space
      .main-secound__contents__container
        .main-secound__contents__container__block
          %p.main-secound__contents__container__block__text{style: 'font-size:16px;'}
            認証番号を再送することもできます。もう一度電話番号を入力して下さい。
          .main-secound__contents__container__block__description
            = link_to "#" ,class:'link-return' do
              電話番号を再度入力する
          %p.main-secound__contents__container__block__text-message.small-text
            ※SMSが届かない場合は
            = link_to "SMS受信設定", "https://www.mercari.com/jp/tos_list/" ,class: 'link-blue'
            を確認して、もう一度電話番号を入力してください。
        

.footer-first
  %ul.footer-first__sections
    %li.footer-first__sections__list
      = link_to "プライバシーポリシー" ,"#"
    %li.footer-first__sections__list
      = link_to "メルカリ利用規約" ,"#"
    %li.footer-first__sections__list
      = link_to "特定商取引に関する表記" ,"#"
  .footer-first__logo
    = link_to "#" do
      = image_tag '//www-mercari-jp.akamaized.net/assets/img/common/common/logo-gray.svg?891577966', class: 'footer__logo__icon'
  %P.footer-first__data
    © 2019 Mercari

app/views/signup/signup5.html.haml
.header-secound
  .header-secound__logo
    = link_to "#" do
      = image_tag "//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?891577966", class: 'header-secound__logo__icon'
  .header-secound__signup-bar
    %ol.header-secound__signup-bar__stepber
      %li.header-secound__signup-bar__stepber--first
        会員情報
        .bubble.red-color
          %span.red-color
      %li.header-secound__signup-bar__stepber--secound
        電話番号認証
        .bubble.red-color
          %span.red-color
      %li.header-secound__signup-bar__stepber--third.red-color-text
        お届け先住所入力
        .bubble.red-color
          %span
      %li.header-secound__signup-bar__stepber--forth
        支払い方法
        .bubble
          %span
      %li.header-secound__signup-bar__stepber--fifth
        完了
        .bubble
.main-secound
  .main-secound__block
    %h2.main-secound__block__title
      発送元・お届け先住所入力
  .main-secound__contents
    .main-secound__contents__container
      = form_for @address, url: signup6_signup_index_path, method: :get do |f|
        .main-secound__contents__container__block
          %p.main-secound__contents__container__block__text
            お名前
          %p.main-secound__contents__container__block__require
            必須
          .main-secound__contents__container__block__form
            = f.text_field :firstname, placeholder:"例）徳川", class:'input-place'
          .main-secound__contents__container__block__form
            = f.text_field :lastname,placeholder:"例）家康", class:'input-place'
        .main-secound__contents__container__block
          %p.main-secound__contents__container__block__text
            お名前カナ
          %p.main-secound__contents__container__block__require
            必須
          .main-secound__contents__container__block__form
            = f.text_field :firstname_kana,placeholder:"例）トクガワ", class:'input-place'
          .main-secound__contents__container__block__form
            = f.text_field :lastname_kana,placeholder:"例）イエヤス", class:'input-place'
        .main-secound__contents__container__block
          %p.main-secound__contents__container__block__text
            郵便番号
          %p.main-secound__contents__container__block__require
            必須
          .main-secound__contents__container__block__form
            = f.text_field :postal_code, placeholder:"例）123-4567", class:'input-place'
        .main-secound__contents__container__block
          %p.main-secound__contents__container__block__text
            都道府県
          %p.main-secound__contents__container__block__require
            必須
          .main-secound__contents__container__block__form
            .main-secound__contents__container__block__form--select-box
              = f.collection_select :prefecture,Prefecture.all, :name, :name,{},class:"prefectures"
        .main-secound__contents__container__block
          %p.main-secound__contents__container__block__text
            市区町村
          %p.main-secound__contents__container__block__require
            必須
          .main-secound__contents__container__block__form
            = f.text_field :municipality, placeholder:"例）大阪市北区",class:'input-place'
        .main-secound__contents__container__block
          %p.main-secound__contents__container__block__text
            番地
            %p.main-secound__contents__container__block__require
              必須
            .main-secound__contents__container__block__form
              = f.text_field :house_number,placeholder:"例）茶屋町1-1-1",class:'input-place'
        .main-secound__contents__container__block
          %p.main-secound__contents__container__block__text
            建物名
            %p.main-secound__contents__container__block__require.gray-color
              任意
            .main-secound__contents__container__block__form
              = f.text_field :building_name,placeholder:"例）柳ビル101", class:'input-place'
        .main-secound__contents__container__block
          %p.main-secound__contents__container__block__text
            電話番号
            %p.main-secound__contents__container__block__require.gray-color
              任意
            .main-secound__contents__container__block__form
              = f.text_field :phone_number,placeholder:"例）09012345678",class:'input-place'
        .main-secound__contents__container__block
          .main-secound__contents__container__block__btn-next
            = f.submit "次へ進む" ,class:'link-white'
          .bottom-space
.footer-first
  %ul.footer-first__sections
    %li.footer-first__sections__list
      = link_to "プライバシーポリシー" ,"#"
    %li.footer-first__sections__list
      = link_to "メルカリ利用規約" ,"#"
    %li.footer-first__sections__list
      = link_to "特定商取引に関する表記" ,"#"
  .footer-first__logo
    = link_to "#" do
      = image_tag '//www-mercari-jp.akamaized.net/assets/img/common/common/logo-gray.svg?891577966', class: 'footer__logo__icon'
  %P.footer-first__data
    © 2019 Mercari

app/views/signup/signup6.html.haml
.header-secound
  .header-secound__logo
    = link_to "#" do
      = image_tag "//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?891577966", class: 'header-secound__logo__icon'
  .header-secound__signup-bar
    %ol.header-secound__signup-bar__stepber
      %li.header-secound__signup-bar__stepber--first
        会員情報
        .bubble.red-color
          %span.red-color
      %li.header-secound__signup-bar__stepber--secound
        電話番号認証
        .bubble.red-color
          %span.red-color
      %li.header-secound__signup-bar__stepber--third
        お届け先住所入力
        .bubble.red-color
          %span.red-color
      %li.header-secound__signup-bar__stepber--forth.red-color-text
        支払い方法
        .bubble.red-color
          %span
      %li.header-secound__signup-bar__stepber--fifth
        完了
        .bubble
.main-secound
  .main-secound__block
    %h2.main-secound__block__title
      支払い方法
  .main-secound__contents
    .main-secound__contents__container
      = form_for @user, url: signup_index_path, method: :post do |f|
        .main-secound__contents__container__block
          %p.main-secound__contents__container__block__text
            カード番号
          %p.main-secound__contents__container__block__require
            必須
          .main-secound__contents__container__block__form
            %input.input-place{placeholder:"半角数字のみ", type:"text"}
          %ul.main-secound__contents__container__block__card
            %li
              = image_tag '//www-mercari-jp.akamaized.net/assets/img/card/visa.svg?917505326', height: '20', width: '49', class: ''
            %li
              = image_tag '//www-mercari-jp.akamaized.net/assets/img/card/master-card.svg?917505326', height: '20px', width: '34px', class: 'card-image'
            %li
              = image_tag '//www-mercari-jp.akamaized.net/assets/img/card/saison-card.svg?917505326', height: '20', width: '30', class: 'card-image'
            %li
              = image_tag '//www-mercari-jp.akamaized.net/assets/img/card/jcb.svg?917505326', height: '20', width: '32', class: 'card-image'
            %li
              = image_tag '//www-mercari-jp.akamaized.net/assets/img/card/american_express.svg?917505326', height: '20', width: '21', class: 'card-image'
            %li
              = image_tag '//www-mercari-jp.akamaized.net/assets/img/card/dinersclub.svg?917505326', height: '20', width: '32', class: 'card-image'
            %li
              = image_tag '//www-mercari-jp.akamaized.net/assets/img/card/discover.svg?917505326', height: '20', width: '32', class: 'card-image'
        .main-secound__contents__container__block
          %p.main-secound__contents__container__block__text
            有効期限
          %p.main-secound__contents__container__block__require
            必須
          .main-secound__contents__container__block__form
            .main-secound__contents__container__block__form--select-box
              %select.prefectures.harf-size
                %option{value: ""} --
                - number = 1
                - while number <= 12 do
                  %option{value: "#{number}"} 
                    = number
                  - number += 1
              %span.word
                月
            .main-secound__contents__container__block__form--select-box
              %select.prefectures.harf-size
                %option{value: ""} --
                - number = 19
                - while number <= 30 do
                  %option{value: "#{number}"} 
                    = number
                  - number += 1
              %span.word
                年
        .main-secound__contents__container__block
          %p.main-secound__contents__container__block__text
            セキュリティーコード
          %p.main-secound__contents__container__block__require
            必須
          .main-secound__contents__container__block__form
            %input.input-place{placeholder:"カード背面4桁もしくは3桁の番号", type:"text"}
          .main-secound__contents__container__block__remarks-column
            %span.question-mark
              ?
            %p.blue-color-text
              カード裏面の番号とは？
        .main-secound__contents__container__block
          .main-secound__contents__container__block__btn-next
            = f.submit "次へ進む" ,class:'link-white'
          .bottom-space


.footer-first
  %ul.footer-first__sections
    %li.footer-first__sections__list
      = link_to "プライバシーポリシー" ,"#"
    %li.footer-first__sections__list
      = link_to "メルカリ利用規約" ,"#"
    %li.footer-first__sections__list
      = link_to "特定商取引に関する表記" ,"#"
  .footer-first__logo
    = link_to "#" do
      = image_tag '//www-mercari-jp.akamaized.net/assets/img/common/common/logo-gray.svg?891577966', class: 'footer__logo__icon'
  %P.footer-first__data
    © 2019 Mercari