config/routes.rb
Rails.application.routes.draw do
  get 'purchase/index'
  get 'purchase/done'
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'items#index'

  resources :signup do
    collection do
      get 'signup'
      get 'signup2'
      get 'signup3'
      get 'signup4'
      get 'signup5'
      get 'signup6'
      get 'signup7'
    end
  end


  resources :items do

    collection do
      get 'search'
      post 'search'
    end
    member do
      get 'purchase'
    end
  end





  resources :users, only: [:show, :identification, :index, :new]

  resources :profiles, only: [:show]

  resources :identifications, only: [:show]

  resources :creditcards, only: [:new, :show] do
    collection do
      post 'show', to: 'creditcards#show'
      post 'pay', to: 'creditcards#pay'
      post 'delete', to: 'creditcards#delete'
    end
    member do
      post 'buy'
    end
  end

  
  
  get 'mypage',to:'mypage#index' 
  namespace :mypage do
    get 'profile'
    put 'profile_update'
    get 'card'
    get 'identification'
    get 'logout'
  end
  
end

app/models/creditcard.rb
class Creditcard < ApplicationRecord
  
  belongs_to :user

end

app/controllers/creditcards_controller.rb
class CreditcardsController < ApplicationController

  require "payjp"

  def new
    card = Creditcard.where(user_id: current_user.id)
    redirect_to action: "show" if card.exists?
  end

  def pay #payjpとCardのデータベース作成を実施します。
    Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
    if params['payjp-token'].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create(
      description: '登録テスト', #なくてもOK
      email: current_user.email, #なくてもOK
      card: params['payjp-token'],
      metadata: {user_id: current_user.id}
      ) #念の為metadataにuser_idを入れましたがなくてもOK
      @card = Creditcard.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to mypage_card_path
      else
        redirect_to action: "pay"
      end
    end
  end

  def delete #PayjpとCardデータベースを削除します
    card = Creditcard.where(user_id: current_user.id).first
    if card.blank?
    else
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(card.customer_id)
      customer.delete
      card.delete
    end
      redirect_to action: "new"
  end

  def show #Cardのデータpayjpに送り情報を取り出します
    card = Creditcard.where(user_id: current_user.id).first
    if card.blank?
      redirect_to action: "new" 
    else
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(card.customer_id)
      @default_card_information = customer.cards.retrieve(card.card_id)
    end
  end

  def buy
    item = Item.find(params[:id])
    card = Creditcard.where(user_id: current_user.id).first
    unless current_user.id == item.seller_id
      if card.blank?
        redirect_to action: "new"
      else
        Payjp.api_key = ENV['PAYJP_PRIVATE_KEY']
        customer = Payjp::Customer.retrieve(card.customer_id)       
        Payjp::Charge.create(
        amount: item.price, #支払金額を入力（itemテーブル等に紐づけても良い）
        customer: card.customer_id, #顧客ID
        currency: 'jpy', #日本円
      )
        item.update(buyer_id: current_user.id)
        redirect_to root_path, notice: "支払いが完了しました"
      end
    else
      redirect_to root_path, notice: "自分の商品は購入できません"
    end

  end


end

app/views/creditcards/_contents.html.haml
.contents
  %section.credicard
    %h2.credicard__title
      支払い方法
    .credicard__content
      .credicard__content__header
        %h3.credicard__content__header-title
          クレジットカード一覧
      .credicard__content__addArea
        .credicard__content__addArea-btn
          =link_to "#" do
            =fa_icon "credit-card", class:"icon"
            クレジットカードを追加する
      %div
        %p.index
          = link_to "#" do
            支払い方法について
            = fa_icon "angle-right", class:"icon"

app/views/creditcards/new.html.haml
= form_tag(pay_creditcards_path, method: :post) do
  %script.payjp-button{"data-key" => ENV["PAYJP_KEY"], :src => "https://checkout.pay.jp", :type => "text/javascript", "data-text": "カード登録","data-submit-text": "カード登録"}

app/views/creditcards/show.html.haml
%label 登録クレジットカード情報
%br
= "**** **** **** " + @default_card_information.last4
%br
- exp_month = @default_card_information.exp_month.to_s
- exp_year = @default_card_information.exp_year.to_s.slice(2,3)
= exp_month + " / " + exp_year
= form_tag(delete_creditcards_path, method: :post, id: 'charge-form',  name: "inputForm") do
  %input{ type: "hidden", name: "card_id", value: "" }
  %button 削除する
= link_to "ホームページに戻る", mypage_path