config/routes.rb
Rails.application.routes.draw do
  get 'purchase/index'
  get 'purchase/done'
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'items#index'

  resources :signup do
    collection do
      get 'signup'
      get 'signup2'
      get 'signup3'
      get 'signup4'
      get 'signup5'
      get 'signup6'
      get 'signup7'
    end
  end


  resources :items do

    collection do
      get 'search'
      post 'search'
    end
    member do
      get 'purchase'
    end
  end





  resources :users, only: [:show, :identification, :index, :new]

  resources :profiles, only: [:show]

  resources :identifications, only: [:show]

  resources :creditcards, only: [:new, :show] do
    collection do
      post 'show', to: 'creditcards#show'
      post 'pay', to: 'creditcards#pay'
      post 'delete', to: 'creditcards#delete'
    end
    member do
      post 'buy'
    end
  end

  
  
  get 'mypage',to:'mypage#index' 
  namespace :mypage do
    get 'profile'
    put 'profile_update'
    get 'card'
    get 'identification'
    get 'logout'
  end
  
end

app/models/item.rb
class Item < ApplicationRecord

  has_many :images
  # has_many :comments
  # has_many :images
  # has_many :likes
  has_many :categories
  belongs_to :buyer, class_name: "User", optional: true
  belongs_to :seller, class_name: "User"
  # belongs_to :user
  
  # # category has_many items の場合
  # def index_items
  #   index_categories = Categoreis.first(4)
  #   index_categories.each do |index_category|
  #     index_items = index_category.items
  #     return index_items
  #   end
  # end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :search
  def index
    # # category has_many items の場合
    # @items = Item.index_items.limit(4).order("id DESC")
    categories_lady = Category.last_four(0)
    categories_man = Category.last_four(1)
    categories_baby = Category.last_four(2)
    categories_cos = Category.last_four(3)

    @items_lady = []
    categories_lady.map {|category| @items_lady << Item.find(category.item_id)}

    @items_man = [] 
    categories_man.map {|category| @items_man << Item.find(category.item_id)}

    @items_baby = []
    categories_baby.map {|category| @items_baby << Item.find(category.item_id)}  

    @items_cos = []
    categories_cos.map {|category| @items_cos << Item.find(category.item_id)}  

  end

  def show
    @items = Item.all
    @item = Item.find(params[:id])
    @image = @item.images
    @category = Category.where(item_id:@item.id)
    @user = User.find(@item.seller_id)
  end

  def new
  end

  def destroy
    seller_id = Item.find(params[:id]).seller_id
    if seller_id == current_user.id
    Category.find_by(item_id:params[:id]).destroy if Category.find_by(item_id:params[:id])
    Image.find_by(item_id:params[:id]).destroy if Image.find_by(item_id:params[:id])
    Item.find(params[:id]).delete
    else
    redirect_to item_path(params[:id])
    end
  end

  def create
    @item = Item.create(name:item_params[:item_name],description:item_params[:item_description],condition:item_params[:item_condition],price:item_params[:item_price],brand:item_params[:item_brand],deliveryfee:item_params[:item_deliveryfee],area:item_params[:item_area],days_to_ship:item_params[:item_days_to_ship],sales_situation:"出品中",likes_count:0,size:item_params[:item_size],deliveryWay:item_params[:item_deliveryWay],seller_id:current_user.id)
    item_params[:file].each do |image|
      Image.create(image:image,item_id:Item.last.id)
    end
    first = Category.create(name:item_params[:item_category_first],item_id:Item.last.id)
    second = first.children.create(name:item_params[:item_category_second][0],item_id:Item.last.id)
    third = second.children.create(name:item_params[:item_category_third][0],item_id:Item.last.id)
  end

  def search
    @search = Item.ransack(params[:q]) #ransackメソッド推奨
    @search_item = @search.result.page(params[:page]).per(100)
    @search_page = @search_item.current_page
    @search_count = @search.result.count
  end


  def edit
    @item = Item.find(params[:id])
    @image = @item.images
    @images = []
    @images_id = []
    @image.each do |image|
      @images << image.image.url
      @images_id << image.id
    end
    if @item.seller_id == current_user.id
      @category = Category.where(item_id:@item.id)
      @category_grandchildren = @category.third
      @category_children = @category.third.parent
      @category_parent = @category.third.parent.parent
    else
      redirect_to root_path
    end 
  end
  
  def update
    @item = Item.find(params[:id])
    @images = @item.images
    if params[:image_delate]
      delete_ids = params[:image_delate].map do |id|
        id.to_i
      end
      redirect_to edit_item_path(@item) and return if delete_ids.uniq == @images.ids
    end

    @item.update(name:item_params[:item_name],description:item_params[:item_description],condition:item_params[:item_condition],price:item_params[:item_price],brand:item_params[:item_brand],deliveryfee:item_params[:item_deliveryfee],area:item_params[:item_area],days_to_ship:item_params[:item_days_to_ship],sales_situation:"出品中",likes_count:0,size:item_params[:item_size],deliveryWay:item_params[:item_deliveryWay],seller_id:current_user.id) 

    
    if item_params[:image_delate].present?
      item_params[:image_delate].each do |image_del|
        Image.delete(image_del)
      end
    end
    if item_params[:file].present?
      item_params[:file].each do |image|
        @image = Image.create(image:image,item_id: @item.id)
      end
    end
    
      redirect_to root_path
  end

  def purchase
    @item = Item.find(params[:id])
    card = Creditcard.where(user_id: current_user.id).first
    if @item.seller_id == current_user.id || @item.buyer_id != nil
      redirect_to item_path(params[:id])
    else
      if card.blank?
        redirect_to new_creditcard_path
      else
        Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
        customer = Payjp::Customer.retrieve(card.customer_id)
        @default_card_information = customer.cards.retrieve(card.card_id)
      end
    end
  end


  private
  def item_params
    attrs = [:item_name,:item_description,:item_condition,:item_price,:item_brand,:item_deliveryfee,:item_area,:item_days_to_ship,:item_sales_situation,:item_size,:item_deliveryWay,:item_category_first,file:[],item_category_second:[],item_category_third:[],image:[],image_delate:[]]
    params.permit(attrs)
  end



end

app/views/items/_brand.html.haml
%ul.pc-header-box-lower__left-brand-wrap
  %li.pc-header-box-lower__left-brand
    %a
      シャネル

app/views/items/_footer.html.haml
.footer
  .footer_top
    .footer_top_center
      .footer_top_center-left
        %h2 スマホでかんたんフリマアプリ
        %p 今すぐ無料ダウンロード
        .footer_top_center-left-icon
          %li
            = image_tag 'mercari_icon.png',width: '68px',class:"mercari_icon"
            = link_to "http://urx2.nu/gBv0" do
              = image_tag 'http://urx2.nu/T4Pd',class:"apple_google"
            = link_to "http://urx2.nu/0CyU" do
              = image_tag 'http://urx2.nu/RlpH',class:"apple_google"
      = image_tag 'mercari_foot.png', class: 'footer_top_center-image'
  .footer_bottom
    .footer_bottom_main.clearfix
      .footer_bottom_main-cell
        %h2 メルカリについて
        %ul
          %li 
            = link_to'会社概要（運営会社）','https://about.mercari.com/',class:"list"
          %li 
            = link_to '採用情報', 'https://careers.mercari.com/',class:"list"
          %li 
            = link_to 'プレスリリース', 'https://about.mercari.com/press/news/',class:"list"
          %li 
            = link_to '公式ブログ', 'https://jp-news.mercari.com/',class:"list"
          %li 
            = link_to 'メルカリロゴ利用ガイドライン', 'https://www.mercari.com/jp/logo-guidelines/',class:"list"
        .footer_bottom_main-cell-icon
          = link_to(content_tag(:i, '', class: 'fab fa-twitter fa-2x'), "https://twitter.com/mercari_jp")
          = link_to(content_tag(:i, '', class: 'fab fa-facebook-square fa-2x'), "https://www.facebook.com/mercarijp")
      .footer_bottom_main-cell
        %h2 ヘルプ＆ガイド
        %ul
          %li 
            = link_to'メルカリガイド','http://urx2.nu/TgTm',class:"list"
          %li 
            = link_to'らくらくメルカリ便','http://urx2.nu/Wk3G',class:"list"
          %li 
            = link_to'ゆうゆうメルカリ便','http://urx2.nu/ZVM7',class:"list"
          %li 
            = link_to'大型メルカリ便','http://urx2.nu/8WnM',class:"list"
          %li 
            = link_to'車体取引ガイド','http://urx2.nu/RGW9',class:"list"
          %li 
            = link_to'メルカリあんしん・あんぜん宣言！','http://urx2.nu/KvFm',class:"list"
          %li 
            = link_to'偽ブランド品撲滅への取り組み','http://urx2.nu/t9VW',class:"list"
          %li 
            = link_to'メルカリボックス','http://urx2.nu/01hS',class:"list"
      .footer_bottom_main-cell 
        %h2 プライバシーと利用規約 
        %ul
          %li 
            = link_to'プライバシーポリシー','http://urx2.nu/PCgW',class:"list"
          %li 
            = link_to'メルカリ利用規約','http://urx2.nu/076l',class:"list"
          %li 
            = link_to'あんしんスマホサポート制度に関する利用規約','http://urx2.nu/VVtt',class:"list"
          %li 
            = link_to'コンプライアンスポリシー','http://urx2.nu/vv4r',class:"list"       
      .footer_bottom_main-cell
        %h2 &ensp;
        %ul
          %li 
            = link_to'個人データの安全管理に係る基本方針','http://urx2.nu/fV0x',class:"list"
          %li 
            = link_to'特定商取引に関する表記','http://urx2.nu/VX7C',class:"list"
          %li 
            = link_to'資金決済法に基づく表示','http://urx2.nu/W2Ex',class:"list"
          %li 
            = link_to'法令遵守と犯罪抑止のために','https://about.mercari.com/sustainability/',class:"list"
          %li 
            = link_to'返品・返金ポリシー','http://urx2.nu/0d4K',class:"list"        
      .footer_bottom_main-cell
        %h2 国
        %ul
          %li 
            = link_to'日本','https://www.mercari.com/jp/',class:"list"        
          %li 
            = link_to'United States','https://www.mercari.com/',class:"list"        

    .footer_bottom_bottom
      = link_to "https://www.mercari.com/jp/" do
        = image_tag 'http://urx2.nu/WUUf',class:"mercari"
      %p © 2019 Mercari

- if user_signed_in?
  = link_to new_item_path, class: "sell_btn" do
    .sell_btn-font 出品
    = fa_icon "camera", class: "icon"
- else
  = link_to new_user_session_path, class: "sell_btn" do
    .sell_btn-font 出品
    = fa_icon "camera", class: "icon"

app/views/items/_header-lower.html.haml
.pc-header-box-lower
  .pc-header-box-lower__left
    %li
      %h2
        = link_to "", "https://www.mercari.com/jp/category/", class: "pc-header-lower__left list-parent"
        %i
          = fa_icon "list-ul"
        %span カテゴリーから探す
        = render partial: 'items/category-header'

    %li
      %h2
        = link_to "", "https://www.mercari.com/jp/category/", class: "pc-header-lower list-brand"
        %i
          = fa_icon "tag"
        %span ブランドから探す
        = render partial: 'items/brand'

  .pc-header-box-lower__right
    %ul.pc-header-box-lower__right-login-nav
      - if user_signed_in?
        .gomypage
          =link_to "/mypage" do
            = image_tag "https://stat.ameba.jp/user_images/20131208/09/tamamorijp/00/00/j/o0480048012773923150.jpg?caw=800", width: '32px'
            %span マイページ
        .todo
          =link_to mypage_path do
            = content_tag(:i, '', class: 'fas fa-check fa-lg')
            %span やることリスト 
        .info
          =link_to mypage_path do
            = content_tag(:i, '', class: 'far fa-bell fa-lg')
            %span お知らせ
        .good
          =link_to mypage_path do
            = content_tag(:i, '', class: 'far fa-heart fa-lg')
            %span いいね!一覧
      - else
        %li.signup-box
          = link_to "新規会員登録", signup_signup_index_path, class: "sp-header-btn header-signup"
        %li.login-box
          = link_to "ログイン", new_user_session_path, class: "sp-header-btn header-login"
    

app/views/items/_header.html.haml
= search_form_for @search, url: search_items_path do |f|
  .pc-header
    .pc-header-box
      .pc-header-box-upper
        %h1
          = link_to root_path do
            =image_tag "https://www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?2921618501", alt: "mercari_icon", width:"134", height: "36"
        .pc-header-box-upper__field--right
          = f.text_field :name_cont ,class:"product-form__input",placeholder: '何かお探しですか？',autocomplete:"off"
          %i.pc-header-box-upper__field--right__search
            = f.submit ("") 
            = fa_icon "search"
      = render partial: 'items/header-lower'

app/views/items/edit.html.haml
.item
  .item_header
    .item_header_icon
      = link_to '/' do
        = image_tag 'http://u0u0.net/QHiY',width:'180px',class:"mercari_icon"
  .item_main
    .item_main_center
      = form_tag("/items/#{@item.id}", method: :put, multipart: true) do 
        .item_main_center-cell1.js-parent-category{ 'data-category': @category_parent.name }
          %h2 商品の情報を入力
        .item_main_center-cell2.js-children-category{ 'data-category': @category_children.name }
          .item_main_center-cell2-center.js-grand-children-category{ 'data-category': @category_grandchildren.name }
            %ul
              %li.left 出品画像
              %li.right_hissu 必須
            %p 最大10枚までアップロードできます
            .drag.js-update-img{'data-img': @images,'data-imgid': @images_id}
              .drag_over
                .drag_center
                  %p ドラッグアンドドロップ
                  %p またはクリックしてファイルをアップロード
              %input{type:"file", class:"file",accept:".jpg,.gif,.png,image/jpeg,image/png"}
              
              .drag_over2
                .drag_center2
                  %p ドラッグアンドドロップ
                  %p またはクリックしてファイルをアップロード
        .item_main_center-cell3
          .item_main_center-cell3-center
            .item_main_center-cell3-center_top
              %ul
                %li.left 商品名
                %li.right_hissu 必須
              %input{name:"item_name", placeholder:"商品名（必須40文字まで）", value: @item.name, required:"true"}
            .item_main_center-cell3-center_bottom
              %ul
                %li.left 商品の説明
                %li.right_hissu 必須
              %textarea{name:"item_description",rows:"5",placeholder:"商品の説明（必須1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に１万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。", required:"true"}= @item.description
        
        
        .item_main_center-cell4
          .item_main_center-cell4-left
            %h5 商品の詳細
          .item_main_center-cell4-right
            = render "editCategory", locals: {category: @category}


            .item_main_center-cell4-right_selectSize.js-item-size{ 'data-size': @item.size }
              %ul
                %li.left サイズ
                %li.right_hissu 必須
              %select{class:"default",name:"item_size", value: @item.size}
                %option{value:"---"} ---
                %option{value:"XXS以下"}XXS以下
                %option{value:"XS(SS)"}XS(SS)
                %option{value:"S"}S
                %option{value:"M"}M
                %option{value:"L"}L
                %option{value:"XL(LL)"}XL(LL)
                %option{value:"2XL(3L)"}2XL(3L)
                %option{value:"3XL(4L)"}3XL(4L)
                %option{value:"4XL(5L)以上"}4XL(5L)以上
                %option{value:"FREE SIZE"}FREE SIZE
              %i.fa.fa-chevron-down

            .item_main_center-cell4-right_selectBrand
              %ul
                %li.left ブランド
                %li.right_nini 任意
              %input{placeholder:"例）シャネル",name:"item_brand", value: @item.brand}

            .item_main_center-cell4-right_selectBox.js-item-condition{ 'data-condition': @item.condition }
              %ul
                %li.left 商品の状態
                %li.right_hissu 必須
              %select{class:"default",name:"item_condition",required:"true"}
                %option{value:"---"} ---
                %option{value:"新品、未使用"}新品、未使用
                %option{value:"未使用に近い"}未使用に近い
                %option{value:"目立った傷や汚れなし"}目立った傷や汚れなし
                %option{value:"やや傷や汚れなし"}やや傷や汚れなし
                %option{value:"傷や汚れあり"}傷や汚れあり
                %option{value:"全体的に状態が悪い"}全体的に状態が悪い
              %i.fa.fa-chevron-down
              
        .item_main_center-cell5
          .item_main_center-cell5-left
            %h5 配送について
            = link_to '?',"http://urx.space/W3Wr" 
          .item_main_center-cell5-right
            .item_main_center-cell5-right_select1.select1.js-item-deliveryfee{ 'data-deliveryfee': @item.deliveryfee }
              %ul
                %li.left 配送料の負担
                %li.right_hissu 必須
              %select{id:'drive',class:"default",name:"item_deliveryfee",required:"true"}
                %option{value:"---"} ---
                %option{value:"送料込み(出品者負担)"}送料込み(出品者負担)
                %option{value:"着払い(購入者負担)"}着払い(購入者負担)
              %i.fa.fa-chevron-down
            .item_main_center-cell5-right_selectBox.driveWay.js-item-deliveryway{ 'data-deliveryWay': @item.deliveryWay }
              %ul
                %li.left 発送の方法
                %li.right_hissu 必須
              %select{class:"default",name:"item_deliveryWay"}
                %option{value:"---"} ---
                %option{value:"未定"}未定
                %option{value:"らくらくメルカリ便"}らくらくメルカリ便
                %option{value:"ゆうメール"}ゆうメール
                %option{value:"レターパック"}レターパック
                %option{value:"普通郵便(定形、定形外)"}普通郵便(定形、定形外)
                %option{value:"クロネコヤマト"}クロネコヤマト
                %option{value:"ゆうパック"}ゆうパック
                %option{value:"クリックポスト"}クリックポスト
                %option{value:"ゆうポケット"}ゆうポケット
              %i.fa.fa-chevron-down
            .item_main_center-cell5-right_selectBox.js-item-area{ 'data-area': @item.area }
              %ul
                %li.left 発送元の地域
                %li.right_hissu 必須
              = select_tag "prefecture", options_from_collection_for_select(Prefecture.all, :name, :name),class: "default", name:"item_area"

              %i.fa.fa-chevron-down

            .item_main_center-cell5-right_selectBox.js-item-ship{ 'data-days_to_ship': @item.days_to_ship }
              %ul
                %li.left 発送までの日数
                %li.right_hissu 必須
              %select{class:"default",name:"item_days_to_ship",required:"true"}
                %option{value:"---"} ---
                %option{value:"１〜２日で発送"}１〜２日で発送
                %option{value:"２〜３日で発送"}２〜３日で発送
                %option{value:"４〜７日で発送"}４〜７日で発送
              %i.fa.fa-chevron-down

        .item_main_center-cell6
          .item_main_center-cell6-center
            .item_main_center-cell6-center_left
              %h5 販売価格(300〜9,999,999)
              = link_to '?',"http://urx.space/W3Wr"
            .item_main_center-cell6-center_right
              .item_main_center-cell6-center_right_top
                %ul
                  %li.left 価格
                  %li.left.right_hissu 必須
                  %input{name:"item_price",placeholder:"例）300",id:"price", value: @item.price, required:"true",type:"number",min:"300",max:"9999999"}
                  %li.right ¥
              .item_main_center-cell6-center_right_main
                .left 販売手数料(10%)
                - num = @item.price*0.1
                #rightUp=num.round()
              .item_main_center-cell6-center_right_bottom
                .left 販売利益
                %h2#rightDown=(@item.price-num).round()
        
        .item_main_center-cell7
          .item_main_center-cell7-center
            %p
              = link_to '禁止されている出品',"https://www.mercari.com/jp/help_center/getting_started/prohibited_items/"
              、
              = link_to '行為',"https://www.mercari.com/jp/help_center/getting_started/prohibited_conduct/"
              を必ずご確認ください。
            %p
              またブランド品でシリアルナンバー等がある場合はご記載ください。
              = link_to '偽ブランドの販売',"https://www.mercari.com/jp/help_center/getting_started/counterfeit_goods/"
              は犯罪であり処罰される可能性があります。
            %p
              また、出品をもちまして
              = link_to '加盟店規約',"https://www.mercari.com/jp/seller_terms/"
              に同意したことになります。
            %input{type:"submit",value:"変更する",class:"go"}
            %input{type:"button",value:"もどる",onclick:"history.back()",class:"back"}
  .item_bottom
    %p.item_bottom_top
      = link_to 'プライバシーポリシー',"https://www.mercari.com/jp/privacy/" 
      = link_to 'メルカリ利用規約',"https://www.mercari.com/jp/tos/"
      = link_to '特定商取引に関する表記',"https://www.mercari.com/jp/tokutei/"
    = link_to new_item_path do
      = image_tag 'http://u0u0.net/YHVI',width:'80px',class:"item_bottom_icon"
    %p.item_bottom_last © 2019 Mercari

app/views/items/search.html.haml
= render partial: 'header'
.item-search
  .item-search-center
    .item-search-center_left
      %i.fa.fa-chevron-down.order
      = search_form_for @search, url: search_items_path ,html: { method: :get } do |e|
        = e.select( :sorts,{ '並び替え': 'id desc', '価格の安い順': 'price asc', '価格の高い順': 'price desc', '出品の古い順': 'updated_at asc', '出品の新しい順': 'updated_at desc' } , { selected: params[:q][:sorts] }, { onchange: 'this.form.submit()'} )
        = e.hidden_field :name_cont,value:"#{params[:q]["name_cont"]}"
      -#   %option いいね！の多い順
      = search_form_for @search, url: search_items_path ,html: { method: :get } do |d|
        .item-search-center_left_detail
          %h3 詳細検索
          .item-search-center_left_detail-keyword
            %i.fas.fa-plus
            %span キーワードを追加する
            = d.text_field :name_cont,placeholder:"例）値下げ",autocomplete:"off"
          .item-search-center_left_detail-category
            %i.fas.fa-list-ul
            %span カテゴリーを選択する
            %i.fa.fa-chevron-down.category
            %select
              %option すべて
              - Categoryall.where(ancestors:"null").each do |cate1|
                %option #{cate1.name}
              -# %option レディース
              -# %option メンズ
              -# %option ベビー・キッズ
              -# %option インテリア・住まい・小物
              -# %option 本・音楽・ゲーム
              -# %option おもちゃ・ホビー・グッズ
              -# %option コスメ・香水・美容
              -# %option 家電・スマホ・カメラ
              -# %option スポーツ・レジャー
              -# %option ハンドメイド
              -# %option チケット
              -# %option 自転車・オートバイ
              -# %option その他
          .item-search-center_left_detail-bland
            %i.fas.fa-tag
            %span ブランド名から探す
            = d.text_field :brand,placeholder:"例）シャネル",autocomplete:"off"
          .item-search-center_left_detail-size
            %i.fas.fa-expand
            %span サイズを指定する
            %i.fa.fa-chevron-down.size
            %select
              %option すべて
              %option 洋服のサイズ
              %option メンズ靴のサイズ
              %option レディース靴のサイズ
              %option スカートのサイズ
              %option キッズ服のサイズ
              %option ベビー・キッズ靴のサイズ
              %option ベビー服のサイズ
              %option テレビのサイズ
              %option カメラレンズのサイズ
              %option オートバイのサイズ
              %option ヘルメットのサイズ
              %option タイヤのサイズ
              %option スキーのサイズ
              %option スノーボードのサイズ
          .item-search-center_left_detail-price
            %i.fas.fa-coins
            %span 価格
            %i.fa.fa-chevron-down.size
            %select#select_price
              %option{value:"1"} 選択してください
              %option{value:"2"} 300 ~ 1000
              %option{value:"3"} 1000 ~ 5000
              %option{value:"4"} 5000 ~ 10000
              %option{value:"5"} 10000 ~ 30000
              %option{value:"6"} 30000 ~ 50000
              %option{value:"7"} 50000 ~
            %input{placeholder:"¥ Min",name:"priceMin"}
            %span &nbsp;~&nbsp;
            %input{placeholder:"¥ Max",name:"priceMax"}
          .item-search-center_left_detail-condition
            %i.fas.fa-star
            %span 商品の状態
            .condition_check
              %ul
                %li
                  %input{type:"checkbox",class:"conditionAll"}
                  %span すべて
                #conditionCheck
                  %li 
                    %input{type:"checkbox",name:"condition[]",value:"新品、未使用"}
                    %span 新品、未使用
                  %li
                    %input{type:"checkbox",name:"condition[]",value:"未使用に近い"}
                    %span 未使用に近い
                  %li 
                    %input{type:"checkbox",name:"condition[]",value:"目立った傷や汚れなし"}
                    %span 目立った傷や汚れなし
                  %li
                    %input{type:"checkbox",name:"condition[]",value:"やや傷や汚れ汚れあり"}
                    %span やや傷や汚れ汚れあり
                  %li 
                    %input{type:"checkbox",name:"condition[]",value:"傷や汚れあり"}
                    %span 傷や汚れあり
                  %li 
                    %input{type:"checkbox",name:"condition[]",value:"全体的に状態が悪い"}
                    %span 全体的に状態が悪い
          .item-search-center_left_detail-deriveryfee
            %i.fas.fa-truck-moving
            %span 配送料の負担
            .deriveryfee_check
              %ul
                %li
                  %input{type:"checkbox",class:"deriveryfeeAll"}
                  %span すべて
                #deriveryfeeCheck
                  %li 
                    %input{type:"checkbox",name:"deriveryfee[]",value:"着払い(購入者負担)"}
                    %span 着払い(購入者負担)
                  %li
                    %input{type:"checkbox",name:"deriveryfee[]",value:"送料込み(出品者負担)"}
                    %span 送料込み(出品者負担)
          .item-search-center_left_detail-situation
            %i.fas.fa-shopping-cart
            %span 販売状況
            .situation_check
              %ul
                %li
                  %input{type:"checkbox",class:"situationAll"}
                  %span すべて
                #situationCheck
                  %li 
                    %input{type:"checkbox",name:"situation[]",value:"販売中"}
                    %span 販売中
                  %li
                    %input{type:"checkbox",name:"situation[]",value:"売り切れ"}
                    %span 売り切れ
          .item-search-center_left_detail-button
            %button{type:"reset",class:"reset_button"}クリア
            %button{type:"submit",class:"submit_button"}完了
    .item-search-center_right
      - if params[:q]["name_cont"] != ""
        %h2.word 
          = params[:q]["name_cont"]
        %span の検索結果
        - if @search_item.length() != 0
          - if @search_count <= 100
            %p.match 1 - #{@search_count}件表示
          - else 
            - if @search_page == 1
              %p.match 1 - 100件表示
            - else
              - if @search_count <= 100*@search_page
                %p.match #{100*(@search_page-1)} - #{@search_count}件表示
              - else
                %p.match #{100*(@search_page-1)} - #{100*@search_page}件表示
        - else
          %p.nomatch 該当する商品が見つかりません。検索条件を変えて、再度お試しください。
      -else
        %h2.noword 新着情報
      .item-search-center_right_show
        = render partial: 'search_item'
      = paginate @search_item
- if params[:q]["name_cont"] != ""
  .show_pankuzu
    - breadcrumb :item_search
    = breadcrumbs  separator: " 　&rsaquo;　 "
- else
  .show_pankuzu
    - breadcrumb :item_search
    = breadcrumbs  separator: ""
= render partial: 'footer'