config/routes.rb
Rails.application.routes.draw do
  get 'purchase/index'
  get 'purchase/done'
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'items#index'

  resources :signup do
    collection do
      get 'signup'
      get 'signup2'
      get 'signup3'
      get 'signup4'
      get 'signup5'
      get 'signup6'
      get 'signup7'
    end
  end


  resources :items do

    collection do
      get 'search'
      post 'search'
    end
    member do
      get 'purchase'
    end
  end





  resources :users, only: [:show, :identification, :index, :new]

  resources :profiles, only: [:show]

  resources :identifications, only: [:show]

  resources :creditcards, only: [:new, :show] do
    collection do
      post 'show', to: 'creditcards#show'
      post 'pay', to: 'creditcards#pay'
      post 'delete', to: 'creditcards#delete'
    end
    member do
      post 'buy'
    end
  end

  
  
  get 'mypage',to:'mypage#index' 
  namespace :mypage do
    get 'profile'
    put 'profile_update'
    get 'card'
    get 'identification'
    get 'logout'
  end
  
end

app/controllers/mypage_controller.rb
class MypageController < ApplicationController
  before_action :require_sign,:search

  def profile_update
    User.find(current_user.id).update(nickname:update_params[:user_nickname],profile_description:update_params[:user_description])
    redirect_to mypage_profile_path, notice: 'プロフィールが更新されました'
  end

  private
  def require_sign
    unless user_signed_in?
      redirect_to root_path
    end
  end
  def update_params
    attrs = [:user_nickname,:user_description]
    params.permit(attrs)
  end
  def search
    @search = Item.ransack(params[:q]) #ransackメソッド推奨
    @search_item = @search.result.page(params[:page]).per(100)
    @search_page = @search_item.current_page
    @search_count = @search.result.count
  end
end

app/views/mypage/_cardRight.html.haml
.contents
  %section.credicard
    %h2.credicard__title
      支払い方法
    .credicard__content
      .credicard__content__header
        %h3.credicard__content__header-title
          クレジットカード一覧
      .credicard__content__addArea
        .credicard__content__addArea-btn
          =link_to new_creditcard_path do
            =fa_icon "credit-card", class:"icon"
            クレジットカードを追加する
      %div
        %p.index
          = link_to "#" do
            支払い方法について
            = fa_icon "angle-right", class:"icon"

app/views/mypage/_identificationRight.html.haml
.contents
  %section.identification
    %h2.identification__title
      本人情報の登録
    .identification__form
      %div
        %p お客さまの本人情報をご登録ください。
        %br 登録されたお名前・生年月日を変更する場合、本人確認書類の提出が必要になります。
        %p.index
          = link_to "#" do
            本人確認書類のアップロードについて
            = fa_icon "angle-right", class:"icon"
      .identification__form__label
        %label お名前
        %p 
          = current_user.firstname
          = current_user.lastname
      .identification__form__label
        %label お名前カナ
        %p 
          = current_user.firstname_kana
          = current_user.lastname_kana
      .identification__form__label
        %label 生年月日
        %p 
          = current_user.birthday.strftime('%Y/%m/%d') 
      .identification__form__label
        %label 郵便番号
        %span.identification__form__label-annotation 任意
        %input.identification__form__label-input{placeholder:"例）1234567"}

      #addressPulldown.identification__form__label
        %label 都道府県
        %span.identification__form__label-annotation 任意
        .identification__form__label-pulldown
          = fa_icon "angle-down", class:"icon"
          %select.addressSelect
            %option{"v-for" => "address in addressList"}
              {{ address }}


              
      .identification__form__label
        %label 市区町村
        %span.identification__form__label-annotation 任意
        %input.identification__form__label-input{placeholder:"例) 横浜市緑区"}
      .identification__form__label
        %label 番地
        %span.identification__form__label-annotation 任意
        %input.identification__form__label-input{placeholder:"例) 青山1−1−1"}
      .identification__form__label
        %label 建物名
        %span.identification__form__label-annotation 任意
        %input.identification__form__label-input{placeholder:"例) 柳ビル103"}
      %button.identification__form__btn 登録する
      .identification__form__label
      %div
        %p.index
          = link_to "#" do
            本人情報の登録について
            = fa_icon "angle-right", class:"icon"

app/views/mypage/_indexRight.html.haml
.contents
  %section.user
    =link_to "#" do
      = image_tag "https://stat.ameba.jp/user_images/20131208/09/tamamorijp/00/00/j/o0480048012773923150.jpg?caw=800"
      %h2.user__name
        = current_user.nickname
      .user__number
        .user__number-comment
          評価
          %span.user__number-comment-num
            0
        .user__number-selled
          出品数
          %span.user__number-selled-num
            0
  %section#tabTop.tab-menu
    %ul.tab-menu__title
      %li.tab-menu__title-list{":class" => "{'active': isActive === '1'}", "@click" => "tabChange('1')",}
        %h3
        お知らせ
      %li.tab-menu__title-list{":class" => "{'active': isActive === '2'}", "@click" => "tabChange('2')"}
        %h3
        やることリスト
    %div.tab-menu__content{"v-if" => "isActive === '1'"}
      %ul.tab-menu__content__lists
        =render partial: 'list'
        =render partial: 'list'
        =render partial: 'list'
        =render partial: 'list'
        =render partial: 'list'
        %li.tab-menu__content__lists-all
          = link_to "#" do
            一覧を見る
    %div.tab-menu__content{"v-else" => "isActive === '2'"}
      %ul.tab-menu__content__lists
        =render partial: 'list'
        =render partial: 'list'
        %li.tab-menu__content__lists-all
          = link_to "#" do
            一覧を見る

  %section#tabUnder.tab-menu
    %h2 購入した商品
    %ul.tab-menu__title
      %li.tab-menu__title-list{":class" => "{'active': isActive === '1'}", "@click" => "tabChange('1')",}
        %h3
        取引中
      %li.tab-menu__title-list{":class" => "{'active': isActive === '2'}", "@click" => "tabChange('2')"}
        %h3
        過去の取引
    %div.tab-menu__content{"v-if" => "isActive === '1'"}
      %ul.tab-menu__content__lists
        =render partial: 'list'
        =render partial: 'list'
        =render partial: 'list'
        =render partial: 'list'
        =render partial: 'list'
        %li.tab-menu__content__lists-all
          = link_to "#" do
            一覧を見る
    %div.tab-menu__content{"v-else" => "isActive === '2'"}
      %ul.tab-menu__content__lists
        =render partial: 'list'
        =render partial: 'list'
        =render partial: 'list'
        %li.tab-menu__content__lists-all
          = link_to "#" do
            一覧を見る

app/views/mypage/_left_navi.html.haml
.left
  %nav.left__navi
    %ul.left__navi-list
      - if left_navi == "index"
        %li.left__navi-list-title
          =link_to mypage_path do
            マイページ
            = fa_icon "angle-right", class:"icon"
      - else
        %li
          =link_to mypage_path do
            マイページ
            = fa_icon "angle-right", class:"icon"
      %li
        =link_to "#" do
          お知らせ
          = fa_icon "angle-right", class:"icon"
      %li
        =link_to "#" do
          やることリスト
          = fa_icon "angle-right", class:"icon"
      %li
        =link_to "#" do
          いいね！一覧
          = fa_icon "angle-right", class:"icon"
      %li
        =link_to new_item_path do
          出品する
          = fa_icon "angle-right", class:"icon"
      %li
        =link_to "#" do
          出品した商品-出品中
          = fa_icon "angle-right", class:"icon"
      %li
        =link_to "#" do
          出品した商品-取引中
          = fa_icon "angle-right", class:"icon"
      %li
        =link_to "#" do
          出品した商品-売却済み
          = fa_icon "angle-right", class:"icon"
      %li
        =link_to "#" do
          購入した商品-取引中
          = fa_icon "angle-right", class:"icon"
      %li
        =link_to "#" do
          購入した商品-過去の取引
          = fa_icon "angle-right", class:"icon"
      %li
        =link_to "#" do
          ニュース一覧
          = fa_icon "angle-right", class:"icon"
      %li
        =link_to "#" do
          評価一覧
          = fa_icon "angle-right", class:"icon"
      %li
        =link_to "#" do
          ガイド
          = fa_icon "angle-right", class:"icon"
      %li
        =link_to "#" do
          お問い合わせ
          = fa_icon "angle-right", class:"icon"
    %h3 メルペイ
    %ul.left__navi-list
      %li
        =link_to "#" do
          売上・振込申請
          = fa_icon "angle-right", class:"icon"
      %li
        =link_to "#" do
          ポイント
          = fa_icon "angle-right", class:"icon"
    %h3 設定
    %ul.left__navi-list
      - if left_navi == "profile"
        %li.left__navi-list-title
          =link_to mypage_profile_path do
            プロフィール
            = fa_icon "angle-right", class:"icon"
      - else
        %li
          =link_to mypage_profile_path do
            プロフィール
            = fa_icon "angle-right", class:"icon"
      %li
        =link_to "#" do
          発送元・お届け先住所変更
          = fa_icon "angle-right", class:"icon"
      - if left_navi == "card"
        %li.left__navi-list-title
          =link_to mypage_card_path do
            支払い方法
            = fa_icon "angle-right", class:"icon"
      - else
        %li
          =link_to mypage_card_path do
            支払い方法
            = fa_icon "angle-right", class:"icon"
      %li
        =link_to "#" do
          メール/パスワード
          = fa_icon "angle-right", class:"icon"
      - if left_navi == "identification"
        %li.left__navi-list-title
          =link_to mypage_identification_path do
            本人情報
            = fa_icon "angle-right", class:"icon"
      - else
        %li
          =link_to mypage_identification_path do
            本人情報
            = fa_icon "angle-right", class:"icon"
      %li
        =link_to "#" do
          電話番号の確認
          = fa_icon "angle-right", class:"icon"
      - if left_navi == "logout"
        %li.left__navi-list-title
          =link_to mypage_logout_path do
            ログアウト
            = fa_icon "angle-right", class:"icon"
      - else
        %li
          =link_to mypage_logout_path do
            ログアウト
            = fa_icon "angle-right", class:"icon"

app/views/mypage/_list.html.haml
%li.tab-menu__content__lists-list
  = link_to "#" do
    %figure
      = image_tag "mercari_profile.png"
    .tab-menu__content__lists-body
      %p 事務局から個別メッセージ「《総額50万円分のポイント♪》TikTok「#メルカリコラボ」キャンペーンスタート！」
      %time
        = fa_icon "clock-o", class:"icon"
        %span 4時間前
    = fa_icon "angle-right", class:"icon"

app/views/mypage/_profileRight.html.haml
.contents
  %section.profile
    %h2.profile__title
      プロフィール
    .profile__form
      .profile__form-name
        = image_tag "https://stat.ameba.jp/user_images/20131208/09/tamamorijp/00/00/j/o0480048012773923150.jpg?caw=800"
        %input{value: "#{current_user.nickname}", type: "text",name:"user_nickname"}
      .profile__form-content
        %textarea{placeholder: "例）こんにちは☆ ご覧いただきありがとうございます！かわいいものやきれいめオフィスカジュアル中心に出品しています。服のサイズは主に9号です。気持ちよくお取引できるよう心がけていますので、商品や発送方法などご質問がありましたらお気軽にどうぞ♪",name:"user_description"}
          = current_user.profile_description
      %button{type:"submit",class:"profile__form-btn"}
        変更する

app/views/mypage/card.html.haml
=render partial: 'items/header'
.mypage_pankuzu
  - breadcrumb :mypage_card
  = breadcrumbs  separator: " 　&rsaquo;　 "
.mypage
  =render partial: 'left_navi',locals: { left_navi: 'card' }
  =render partial: 'cardRight'
=render partial: 'items/footer'

app/views/mypage/identification.html.haml
=render partial: 'items/header'
.mypage_pankuzu
  - breadcrumb :mypage_identification
  = breadcrumbs  separator: " 　&rsaquo;　 "
.mypage
  =render partial: 'left_navi',locals: { left_navi: 'identification' }
  =render partial: 'identificationRight'
=render partial: 'items/footer'

app/views/mypage/index.html.haml
=render partial: 'items/header'
.mypage_pankuzu
  - breadcrumb :mypage
  = breadcrumbs  separator: " 　&rsaquo;　 "
.mypage
  =render partial: 'left_navi',locals: { left_navi: 'index' }
  =render partial: 'indexRight'
=render partial: 'items/footer'

app/views/mypage/logout.html.haml
=render partial: 'items/header'
.mypage_pankuzu
  - breadcrumb :mypage_logout
  = breadcrumbs  separator: " 　&rsaquo;　 "
.mypage
  =render partial: 'left_navi',locals: { left_navi: 'logout' }
  .contents
    .contents__signout-block
      = link_to "ログアウト", destroy_user_session_path,method: :delete,class:"contents__signout-block__btn__red"
        
= render partial: 'items/footer'

app/views/mypage/profile.html.haml
=render partial: 'items/header'
.mypage_pankuzu
  - breadcrumb :mypage_profile
  = breadcrumbs  separator: " 　&rsaquo;　 "
  .notifications
    - flash.each do |key, value|
      = content_tag(:div, value, class: key)
= form_tag("/mypage/profile_update", method: :put) do
  .mypage
    =render partial: 'left_navi',locals: { left_navi: 'profile' }
    =render partial: 'profileRight'
  =render partial: 'items/footer'